services:
  - type: web
    name: skin-prediction-backend
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.10.13"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: MONGO_DBNAME
        value: skin_prediction_db
      - key: FRONTEND_URL
        sync: false
      - key: LOG_LEVEL
        value: INFO
